#ifndef _AUDIO_JIT_MLIR_LIB_H
#define _AUDIO_JIT_MLIR_LIB_H
extern int STYPE_AUDIO_JIT_SYM;
extern int STYPE_AUDIO_JIT_INLINE_SYM;
extern int STYPE_AUDIO_JIT_BUILTIN_HANDLER;
extern int STYPE_AUDIO_JIT_INLINE_LAMBDA;
extern int STYPE_AUDIO_JIT_SYNTH_INLET;
extern int STYPE_AUDIO_JIT_LOCAL_ARRAY;
#endif
