#line 1 "lang/lex.yy.c"

#line 3 "lang/lex.yy.c"

#define  YY_INT_ALIGNED short int

/* A lexical scanner generated by flex */

#define FLEX_SCANNER
#define YY_FLEX_MAJOR_VERSION 2
#define YY_FLEX_MINOR_VERSION 6
#define YY_FLEX_SUBMINOR_VERSION 4
#if YY_FLEX_SUBMINOR_VERSION > 0
#define FLEX_BETA
#endif

/* First, we deal with  platform-specific or compiler-specific issues. */

/* begin standard C headers. */
#include <stdio.h>
#include <string.h>
#include <errno.h>
#include <stdlib.h>

/* end standard C headers. */

/* flex integer type definitions */

#ifndef FLEXINT_H
#define FLEXINT_H

/* C99 systems have <inttypes.h>. Non-C99 systems may or may not. */

#if defined (__STDC_VERSION__) && __STDC_VERSION__ >= 199901L

/* C99 says to define __STDC_LIMIT_MACROS before including stdint.h,
 * if you want the limit (max/min) macros for int types. 
 */
#ifndef __STDC_LIMIT_MACROS
#define __STDC_LIMIT_MACROS 1
#endif

#include <inttypes.h>
typedef int8_t flex_int8_t;
typedef uint8_t flex_uint8_t;
typedef int16_t flex_int16_t;
typedef uint16_t flex_uint16_t;
typedef int32_t flex_int32_t;
typedef uint32_t flex_uint32_t;
#else
typedef signed char flex_int8_t;
typedef short int flex_int16_t;
typedef int flex_int32_t;
typedef unsigned char flex_uint8_t; 
typedef unsigned short int flex_uint16_t;
typedef unsigned int flex_uint32_t;

/* Limits of integral types. */
#ifndef INT8_MIN
#define INT8_MIN               (-128)
#endif
#ifndef INT16_MIN
#define INT16_MIN              (-32767-1)
#endif
#ifndef INT32_MIN
#define INT32_MIN              (-2147483647-1)
#endif
#ifndef INT8_MAX
#define INT8_MAX               (127)
#endif
#ifndef INT16_MAX
#define INT16_MAX              (32767)
#endif
#ifndef INT32_MAX
#define INT32_MAX              (2147483647)
#endif
#ifndef UINT8_MAX
#define UINT8_MAX              (255U)
#endif
#ifndef UINT16_MAX
#define UINT16_MAX             (65535U)
#endif
#ifndef UINT32_MAX
#define UINT32_MAX             (4294967295U)
#endif

#ifndef SIZE_MAX
#define SIZE_MAX               (~(size_t)0)
#endif

#endif /* ! C99 */

#endif /* ! FLEXINT_H */

/* begin standard C++ headers. */

/* TODO: this is always defined, so inline it */
#define yyconst const

#if defined(__GNUC__) && __GNUC__ >= 3
#define yynoreturn __attribute__((__noreturn__))
#else
#define yynoreturn
#endif

/* Returned upon end-of-file. */
#define YY_NULL 0

/* Promotes a possibly negative, possibly signed char to an
 *   integer in range [0..255] for use as an array index.
 */
#define YY_SC_TO_UI(c) ((YY_CHAR) (c))

/* Enter a start condition.  This macro really ought to take a parameter,
 * but we do it the disgusting crufty way forced on us by the ()-less
 * definition of BEGIN.
 */
#define BEGIN (yy_start) = 1 + 2 *
/* Translate the current start state into a value that can be later handed
 * to BEGIN to return to the state.  The YYSTATE alias is for lex
 * compatibility.
 */
#define YY_START (((yy_start) - 1) / 2)
#define YYSTATE YY_START
/* Action number for EOF rule of a given start state. */
#define YY_STATE_EOF(state) (YY_END_OF_BUFFER + state + 1)
/* Special action meaning "start processing a new file". */
#define YY_NEW_FILE yyrestart( yyin  )
#define YY_END_OF_BUFFER_CHAR 0

/* Size of default input buffer. */
#ifndef YY_BUF_SIZE
#ifdef __ia64__
/* On IA-64, the buffer size is 16k, not 8k.
 * Moreover, YY_BUF_SIZE is 2*YY_READ_BUF_SIZE in the general case.
 * Ditto for the __ia64__ case accordingly.
 */
#define YY_BUF_SIZE 32768
#else
#define YY_BUF_SIZE 16384
#endif /* __ia64__ */
#endif

/* The state buf must be large enough to hold one state per character in the main buffer.
 */
#define YY_STATE_BUF_SIZE   ((YY_BUF_SIZE + 2) * sizeof(yy_state_type))

#ifndef YY_TYPEDEF_YY_BUFFER_STATE
#define YY_TYPEDEF_YY_BUFFER_STATE
typedef struct yy_buffer_state *YY_BUFFER_STATE;
#endif

#ifndef YY_TYPEDEF_YY_SIZE_T
#define YY_TYPEDEF_YY_SIZE_T
typedef size_t yy_size_t;
#endif

extern int yyleng;

extern FILE *yyin, *yyout;

#define EOB_ACT_CONTINUE_SCAN 0
#define EOB_ACT_END_OF_FILE 1
#define EOB_ACT_LAST_MATCH 2
    
    /* Note: We specifically omit the test for yy_rule_can_match_eol because it requires
     *       access to the local variable yy_act. Since yyless() is a macro, it would break
     *       existing scanners that call yyless() from OUTSIDE yylex.
     *       One obvious solution it to make yy_act a global. I tried that, and saw
     *       a 5% performance hit in a non-yylineno scanner, because yy_act is
     *       normally declared as a register variable-- so it is not worth it.
     */
    #define  YY_LESS_LINENO(n) \
            do { \
                int yyl;\
                for ( yyl = n; yyl < yyleng; ++yyl )\
                    if ( yytext[yyl] == '\n' )\
                        --yylineno;\
            }while(0)
    #define YY_LINENO_REWIND_TO(dst) \
            do {\
                const char *p;\
                for ( p = yy_cp-1; p >= (dst); --p)\
                    if ( *p == '\n' )\
                        --yylineno;\
            }while(0)
    
/* Return all but the first "n" matched characters back to the input stream. */
#define yyless(n) \
	do \
		{ \
		/* Undo effects of setting up yytext. */ \
        int yyless_macro_arg = (n); \
        YY_LESS_LINENO(yyless_macro_arg);\
		*yy_cp = (yy_hold_char); \
		YY_RESTORE_YY_MORE_OFFSET \
		(yy_c_buf_p) = yy_cp = yy_bp + yyless_macro_arg - YY_MORE_ADJ; \
		YY_DO_BEFORE_ACTION; /* set up yytext again */ \
		} \
	while ( 0 )
#define unput(c) yyunput( c, (yytext_ptr)  )

#ifndef YY_STRUCT_YY_BUFFER_STATE
#define YY_STRUCT_YY_BUFFER_STATE
struct yy_buffer_state
	{
	FILE *yy_input_file;

	char *yy_ch_buf;		/* input buffer */
	char *yy_buf_pos;		/* current position in input buffer */

	/* Size of input buffer in bytes, not including room for EOB
	 * characters.
	 */
	int yy_buf_size;

	/* Number of characters read into yy_ch_buf, not including EOB
	 * characters.
	 */
	int yy_n_chars;

	/* Whether we "own" the buffer - i.e., we know we created it,
	 * and can realloc() it to grow it, and should free() it to
	 * delete it.
	 */
	int yy_is_our_buffer;

	/* Whether this is an "interactive" input source; if so, and
	 * if we're using stdio for input, then we want to use getc()
	 * instead of fread(), to make sure we stop fetching input after
	 * each newline.
	 */
	int yy_is_interactive;

	/* Whether we're considered to be at the beginning of a line.
	 * If so, '^' rules will be active on the next match, otherwise
	 * not.
	 */
	int yy_at_bol;

    int yy_bs_lineno; /**< The line count. */
    int yy_bs_column; /**< The column count. */

	/* Whether to try to fill the input buffer when we reach the
	 * end of it.
	 */
	int yy_fill_buffer;

	int yy_buffer_status;

#define YY_BUFFER_NEW 0
#define YY_BUFFER_NORMAL 1
	/* When an EOF's been seen but there's still some text to process
	 * then we mark the buffer as YY_EOF_PENDING, to indicate that we
	 * shouldn't try reading from the input source any more.  We might
	 * still have a bunch of tokens to match, though, because of
	 * possible backing-up.
	 *
	 * When we actually see the EOF, we change the status to "new"
	 * (via yyrestart()), so that the user can continue scanning by
	 * just pointing yyin at a new input file.
	 */
#define YY_BUFFER_EOF_PENDING 2

	};
#endif /* !YY_STRUCT_YY_BUFFER_STATE */

/* Stack of input buffers. */
static size_t yy_buffer_stack_top = 0; /**< index of top of stack. */
static size_t yy_buffer_stack_max = 0; /**< capacity of stack. */
static YY_BUFFER_STATE * yy_buffer_stack = NULL; /**< Stack as an array. */

/* We provide macros for accessing buffer states in case in the
 * future we want to put the buffer states in a more general
 * "scanner state".
 *
 * Returns the top of the stack, or NULL.
 */
#define YY_CURRENT_BUFFER ( (yy_buffer_stack) \
                          ? (yy_buffer_stack)[(yy_buffer_stack_top)] \
                          : NULL)
/* Same as previous macro, but useful when we know that the buffer stack is not
 * NULL or when we need an lvalue. For internal use only.
 */
#define YY_CURRENT_BUFFER_LVALUE (yy_buffer_stack)[(yy_buffer_stack_top)]

/* yy_hold_char holds the character lost when yytext is formed. */
static char yy_hold_char;
static int yy_n_chars;		/* number of characters read into yy_ch_buf */
int yyleng;

/* Points to current character in buffer. */
static char *yy_c_buf_p = NULL;
static int yy_init = 0;		/* whether we need to initialize */
static int yy_start = 0;	/* start state number */

/* Flag which is used to allow yywrap()'s to do buffer switches
 * instead of setting up a fresh yyin.  A bit of a hack ...
 */
static int yy_did_buffer_switch_on_eof;

void yyrestart ( FILE *input_file  );
void yy_switch_to_buffer ( YY_BUFFER_STATE new_buffer  );
YY_BUFFER_STATE yy_create_buffer ( FILE *file, int size  );
void yy_delete_buffer ( YY_BUFFER_STATE b  );
void yy_flush_buffer ( YY_BUFFER_STATE b  );
void yypush_buffer_state ( YY_BUFFER_STATE new_buffer  );
void yypop_buffer_state ( void );

static void yyensure_buffer_stack ( void );
static void yy_load_buffer_state ( void );
static void yy_init_buffer ( YY_BUFFER_STATE b, FILE *file  );
#define YY_FLUSH_BUFFER yy_flush_buffer( YY_CURRENT_BUFFER )

YY_BUFFER_STATE yy_scan_buffer ( char *base, yy_size_t size  );
YY_BUFFER_STATE yy_scan_string ( const char *yy_str  );
YY_BUFFER_STATE yy_scan_bytes ( const char *bytes, int len  );

void *yyalloc ( yy_size_t  );
void *yyrealloc ( void *, yy_size_t  );
void yyfree ( void *  );

#define yy_new_buffer yy_create_buffer
#define yy_set_interactive(is_interactive) \
	{ \
	if ( ! YY_CURRENT_BUFFER ){ \
        yyensure_buffer_stack (); \
		YY_CURRENT_BUFFER_LVALUE =    \
            yy_create_buffer( yyin, YY_BUF_SIZE ); \
	} \
	YY_CURRENT_BUFFER_LVALUE->yy_is_interactive = is_interactive; \
	}
#define yy_set_bol(at_bol) \
	{ \
	if ( ! YY_CURRENT_BUFFER ){\
        yyensure_buffer_stack (); \
		YY_CURRENT_BUFFER_LVALUE =    \
            yy_create_buffer( yyin, YY_BUF_SIZE ); \
	} \
	YY_CURRENT_BUFFER_LVALUE->yy_at_bol = at_bol; \
	}
#define YY_AT_BOL() (YY_CURRENT_BUFFER_LVALUE->yy_at_bol)

/* Begin user sect3 */
typedef flex_uint8_t YY_CHAR;

FILE *yyin = NULL, *yyout = NULL;

typedef int yy_state_type;

extern int yylineno;
int yylineno = 1;

extern char *yytext;
#ifdef yytext_ptr
#undef yytext_ptr
#endif
#define yytext_ptr yytext

static yy_state_type yy_get_previous_state ( void );
static yy_state_type yy_try_NUL_trans ( yy_state_type current_state  );
static int yy_get_next_buffer ( void );
static void yynoreturn yy_fatal_error ( const char* msg  );

/* Done after the current pattern has been matched and before the
 * corresponding action - sets up yytext.
 */
#define YY_DO_BEFORE_ACTION \
	(yytext_ptr) = yy_bp; \
	yyleng = (int) (yy_cp - yy_bp); \
	(yy_hold_char) = *yy_cp; \
	*yy_cp = '\0'; \
	(yy_c_buf_p) = yy_cp;
#define YY_NUM_RULES 77
#define YY_END_OF_BUFFER 78
/* This struct is not used in this scanner,
   but its presence is necessary. */
struct yy_trans_info
	{
	flex_int32_t yy_verify;
	flex_int32_t yy_nxt;
	};
static const flex_int16_t yy_accept[183] =
    {   0,
        0,    0,    0,    0,    0,    0,   78,   76,   68,   69,
       76,   76,   67,   75,   58,   25,   76,   57,   57,   27,
       57,   57,   16,   50,   52,   64,   57,   57,   57,   75,
       32,   12,   28,   13,   32,   37,   32,   32,   32,   32,
       32,   32,   32,   32,   32,   32,   57,   48,   42,   77,
       38,   41,   47,   77,   46,   68,   62,    0,   49,    0,
       67,   75,   33,   24,    0,    0,    5,   54,   50,   52,
       65,    0,   54,   54,    0,    0,   52,   51,   63,   60,
       61,   59,   56,   34,   32,    0,    0,   32,   32,   32,
       32,    1,   32,   20,   32,    3,   32,   32,   32,   19,

       32,   32,   32,   31,   32,   32,   32,   32,   55,   26,
       42,   43,   39,   40,   47,    0,    0,   49,    0,   33,
       74,    0,    0,    0,    0,    0,    0,    9,    0,   54,
       53,   35,   44,    4,   32,   32,   32,   30,   32,    2,
       32,   32,   32,   32,   32,   32,   32,   32,   32,   45,
       72,   73,    0,   70,   71,    0,    0,   34,   22,   32,
       32,   32,   32,   32,   15,   18,   21,    7,   17,   11,
       32,    0,   32,    8,   32,   10,   32,   23,    6,   14,
       29,    0
    } ;

static const YY_CHAR yy_ec[256] =
    {   0,
        1,    1,    1,    1,    1,    1,    1,    1,    2,    3,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    2,    4,    5,    6,    7,    8,    9,   10,   11,
       12,   13,   14,   15,   16,   17,   18,   19,   20,   20,
       20,   20,   20,   20,   20,   21,   21,   22,   15,   23,
       24,   25,   26,   27,   28,   28,   28,   28,   28,   28,
       29,   29,   29,   29,   29,   29,   29,   29,   29,   29,
       29,   29,   29,   29,   29,   29,   29,   29,   29,   29,
       30,   31,   32,    7,   33,   34,   35,   36,   37,   38,

       39,   40,   29,   41,   42,   29,   29,   43,   44,   45,
       46,   47,   29,   48,   49,   50,   51,   52,   53,   54,
       55,   29,   56,   57,   58,    7,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,

        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1
    } ;

static const YY_CHAR yy_meta[59] =
    {   0,
        1,    1,    2,    3,    1,    1,    3,    3,    3,    4,
        1,    1,    3,    3,    1,    3,    5,    6,    7,    7,
        7,    3,    3,    3,    3,    3,    3,    8,    9,   10,
       11,    1,    9,   12,    8,    8,    8,    8,    8,    8,
        9,    9,    9,    9,    9,    9,    9,    9,    9,    9,
        9,    9,    9,    9,    9,   12,    3,    1
    } ;

static const flex_int16_t yy_base[200] =
    {   0,
        0,    0,   28,   29,   27,   30,  337,  550,  326,  550,
      286,   60,    0,    0,   88,  299,  254,  270,  550,    0,
        0,   49,   56,   99,  104,  257,  251,  224,  218,  196,
       49,  550,  550,  550,   60,  181,   63,  104,  111,  110,
       64,  113,  121,  134,  142,  144,   73,  550,    0,   31,
      550,  550,    0,  153,  550,  183,  550,   95,  550,  102,
        0,    0,    0,  550,  173,  185,  550,  116,  146,  177,
        0,   54,  150,  157,  182,    0,  189,  550,  550,    0,
        0,    0,    0,    0,  161,  117,  108,  189,  163,  196,
      170,  204,  206,  210,  213,  214,  220,  223,  227,  229,

      233,  231,  237,  234,  238,  244,  248,  251,    0,    0,
        0,  550,  550,  550,    0,  104,  187,  253,  266,    0,
      550,  122,  267,  273,  117,  107,    0,  550,   92,  275,
        0,  550,  550,  270,  281,  283,  284,  285,  286,  287,
      288,  289,  291,  294,  305,  308,  309,  311,  312,  550,
      550,  550,  339,  550,  550,   89,   71,    0,  313,  316,
      327,  333,  335,  342,  338,  343,  344,  349,  352,  353,
      357,   62,  359,  360,  362,  366,  368,  370,  373,  375,
      376,  550,  412,  424,  436,  448,  458,  462,  471,  478,
      488,  498,  510,  521,  527,  530,  533,  536,  540

    } ;

static const flex_int16_t yy_def[200] =
    {   0,
      182,    1,  183,  183,  184,  184,  182,  182,  182,  182,
      182,  185,  186,  187,  188,  182,  189,  182,  182,  187,
      187,  187,  182,  182,  182,  182,  187,  187,  187,  187,
      190,  182,  182,  182,  190,  182,  190,  190,  190,  190,
      190,  190,  190,  190,  190,  190,  187,  182,  191,  192,
      182,  182,  193,  182,  182,  182,  182,  185,  182,  194,
      186,  187,  195,  182,  182,  182,  182,  187,  182,  182,
      187,  182,  182,  182,  182,  196,  182,  182,  182,  187,
      187,  187,  187,  197,  190,  182,  182,  190,  190,  190,
      190,  190,  190,  190,  190,  190,  190,  190,  190,  190,

      190,  190,  190,  190,  190,  190,  190,  190,  187,  187,
      191,  182,  182,  182,  193,  182,  185,  185,  194,  195,
      182,  182,  182,  182,  182,  182,  198,  182,  199,  182,
      196,  182,  182,  190,  190,  190,  190,  190,  190,  190,
      190,  190,  190,  190,  190,  190,  190,  190,  190,  182,
      182,  182,  182,  182,  182,  198,  182,  197,  190,  190,
      190,  190,  190,  190,  190,  190,  190,  190,  190,  190,
      190,  182,  190,  190,  190,  190,  190,  190,  190,  190,
      190,    0,  182,  182,  182,  182,  182,  182,  182,  182,
      182,  182,  182,  182,  182,  182,  182,  182,  182

    } ;

static const flex_int16_t yy_nxt[609] =
    {   0,
        8,    9,   10,   11,   12,   13,   14,   15,   16,   17,
       18,   19,   20,   21,   19,   22,   23,   21,   24,   25,
       25,   26,   27,   28,   29,    8,   30,   31,   31,   32,
       33,   34,   35,   36,   37,   31,   31,   31,   38,   39,
       31,   40,   41,   42,   31,   43,   31,   31,   31,   44,
       31,   31,   45,   31,   46,   19,   47,   48,   50,   50,
       54,   51,   51,   54,   59,   68,   84,   69,   70,   70,
      128,  129,   72,   71,   73,   73,   73,   84,   86,  129,
       84,   84,   55,   52,   52,   55,  113,  172,  114,   86,
       60,   62,   86,   86,   62,   62,   62,  109,  121,   59,

       62,   62,   97,   62,   62,   62,  118,   88,  157,   62,
       62,   62,   62,   62,   62,   74,  155,   75,   75,   75,
       74,   84,   77,   77,   77,   60,  154,   84,   84,  110,
       84,  151,  119,   86,   73,   73,   73,  150,   84,   86,
       86,  133,   86,   78,   62,   91,   89,   98,  132,   94,
       86,   84,   76,   95,   96,   92,   93,   90,   99,   84,
      100,   84,   74,   86,   75,   75,   75,  101,  130,  130,
      130,   86,  102,   86,  103,   73,   73,   73,   84,  104,
       84,  105,  121,  107,   56,  108,  116,   84,  106,   65,
       86,   59,   86,   74,  122,   77,   77,   77,   74,   86,

       75,   75,   75,  123,  124,   74,   84,   77,   77,   77,
       65,  135,  137,   84,   87,   65,   78,   60,   86,   65,
       65,   84,   83,   84,   65,   86,  134,   84,   78,  125,
       84,   84,   65,   86,  126,   86,   65,   84,  127,   86,
       84,   82,   86,   86,   84,  136,   84,   81,   84,   86,
       84,   84,   86,  138,   84,   84,   86,   59,   86,  139,
       86,   84,   86,   86,  142,   84,   86,   86,   84,  140,
      118,  143,  141,   86,   80,  145,  152,   86,   79,  144,
       86,   67,  121,   60,   66,  153,  153,   84,  146,  149,
      147,  153,  153,  130,  130,  130,  119,  148,   84,   86,

       84,   84,   84,   84,   84,   84,   84,   64,   84,   57,
       86,   84,   86,   86,   86,   86,   86,   86,   86,  159,
       86,  160,   84,   86,  163,   84,   84,   56,   84,   84,
       84,  162,  161,   84,   86,  165,  182,   86,   86,  164,
       86,   86,   86,  166,   84,   86,  168,  169,  121,  167,
       84,  170,   84,  182,  171,   84,   86,   65,   65,   84,
       84,   84,   86,  173,   86,  174,   84,   86,  182,   84,
       84,   86,   86,   86,   84,  176,   84,   84,   86,   84,
      175,   86,   86,   84,  177,   84,   86,   84,   86,   86,
       84,   86,   84,   84,  178,   86,  182,   86,  182,   86,

      182,  182,   86,  179,   86,   86,  181,  182,  182,  182,
      182,  180,   49,   49,   49,   49,   49,   49,   49,   49,
       49,   49,   49,   49,   53,   53,   53,   53,   53,   53,
       53,   53,   53,   53,   53,   53,   58,  182,   58,   58,
       58,   58,   58,   58,   58,   58,   58,   58,   61,  182,
       61,   61,   61,   61,   61,   61,   61,   61,   61,   61,
       62,  182,   62,   62,   63,  182,   63,   63,  182,   63,
       63,   65,  182,   65,  182,   65,   65,   65,   65,   65,
       65,   65,   65,   85,   85,   85,   85,   85,  111,  111,
      111,  111,  111,  111,  111,  111,  111,  111,  112,  112,

      112,  112,  112,  112,  112,  112,  112,  112,  112,  112,
      115,  115,  115,  115,  115,  115,  115,  115,  115,  115,
      115,  117,  182,  117,  117,  117,  117,  117,  117,  117,
      117,  117,  117,  120,  120,  120,  131,  131,   84,   84,
       84,   84,  156,  156,  158,  182,  182,  158,  158,    7,
      182,  182,  182,  182,  182,  182,  182,  182,  182,  182,
      182,  182,  182,  182,  182,  182,  182,  182,  182,  182,
      182,  182,  182,  182,  182,  182,  182,  182,  182,  182,
      182,  182,  182,  182,  182,  182,  182,  182,  182,  182,
      182,  182,  182,  182,  182,  182,  182,  182,  182,  182,

      182,  182,  182,  182,  182,  182,  182,  182
    } ;

static const flex_int16_t yy_chk[609] =
    {   0,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    3,    4,
        5,    3,    4,    6,   12,   22,   31,   22,   22,   22,
       72,   72,   23,   22,   23,   23,   23,   35,   31,  172,
       37,   41,    5,    3,    4,    6,   50,  157,   50,   35,
       12,   15,   37,   41,   15,   15,   15,   47,  156,   58,

       15,   15,   41,   15,   15,   15,   60,   37,  129,   15,
       15,   15,   15,   15,   15,   24,  126,   24,   24,   24,
       25,   38,   25,   25,   25,   58,  125,   40,   39,   47,
       42,  122,   60,   38,   68,   68,   68,  116,   43,   40,
       39,   87,   42,   25,   15,   39,   38,   42,   86,   40,
       43,   44,   24,   40,   40,   39,   39,   38,   42,   45,
       43,   46,   69,   44,   69,   69,   69,   43,   73,   73,
       73,   45,   44,   46,   44,   74,   74,   74,   85,   44,
       89,   44,   65,   45,   56,   46,   54,   91,   44,   66,
       85,  117,   89,   70,   66,   70,   70,   70,   75,   91,

       75,   75,   75,   66,   66,   77,   88,   77,   77,   77,
       66,   89,   91,   90,   36,   66,   70,  117,   88,   66,
       66,   92,   30,   93,   66,   90,   88,   94,   77,   66,
       95,   96,   66,   92,   66,   93,   66,   97,   66,   94,
       98,   29,   95,   96,   99,   90,  100,   28,  102,   97,
      101,  104,   98,   93,  103,  105,   99,  118,  100,   95,
      102,  106,  101,  104,   99,  107,  103,  105,  108,   97,
      119,  101,   98,  106,   27,  103,  123,  107,   26,  102,
      108,   18,  124,  118,   17,  123,  123,  134,  105,  108,
      106,  124,  124,  130,  130,  130,  119,  107,  135,  134,

      136,  137,  138,  139,  140,  141,  142,   16,  143,   11,
      135,  144,  136,  137,  138,  139,  140,  141,  142,  135,
      143,  136,  145,  144,  141,  146,  147,    9,  148,  149,
      159,  139,  137,  160,  145,  143,    7,  146,  147,  142,
      148,  149,  159,  144,  161,  160,  146,  147,  153,  145,
      162,  148,  163,    0,  149,  165,  161,  153,  153,  164,
      166,  167,  162,  160,  163,  161,  168,  165,    0,  169,
      170,  164,  166,  167,  171,  163,  173,  174,  168,  175,
      162,  169,  170,  176,  164,  177,  171,  178,  173,  174,
      179,  175,  180,  181,  171,  176,    0,  177,    0,  178,

        0,    0,  179,  173,  180,  181,  177,    0,    0,    0,
        0,  175,  183,  183,  183,  183,  183,  183,  183,  183,
      183,  183,  183,  183,  184,  184,  184,  184,  184,  184,
      184,  184,  184,  184,  184,  184,  185,    0,  185,  185,
      185,  185,  185,  185,  185,  185,  185,  185,  186,    0,
      186,  186,  186,  186,  186,  186,  186,  186,  186,  186,
      187,    0,  187,  187,  188,    0,  188,  188,    0,  188,
      188,  189,    0,  189,    0,  189,  189,  189,  189,  189,
      189,  189,  189,  190,  190,  190,  190,  190,  191,  191,
      191,  191,  191,  191,  191,  191,  191,  191,  192,  192,

      192,  192,  192,  192,  192,  192,  192,  192,  192,  192,
      193,  193,  193,  193,  193,  193,  193,  193,  193,  193,
      193,  194,    0,  194,  194,  194,  194,  194,  194,  194,
      194,  194,  194,  195,  195,  195,  196,  196,  197,  197,
      197,  197,  198,  198,  199,    0,    0,  199,  199,  182,
      182,  182,  182,  182,  182,  182,  182,  182,  182,  182,
      182,  182,  182,  182,  182,  182,  182,  182,  182,  182,
      182,  182,  182,  182,  182,  182,  182,  182,  182,  182,
      182,  182,  182,  182,  182,  182,  182,  182,  182,  182,
      182,  182,  182,  182,  182,  182,  182,  182,  182,  182,

      182,  182,  182,  182,  182,  182,  182,  182
    } ;

/* Table of booleans, true if rule could match eol. */
static const flex_int32_t yy_rule_can_match_eol[78] =
    {   0,
0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 
    0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 
    0, 0, 1, 1, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 
    0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0,     };

static yy_state_type yy_last_accepting_state;
static char *yy_last_accepting_cpos;

extern int yy_flex_debug;
int yy_flex_debug = 0;

/* The intent behind this definition is that it'll catch
 * any uses of REJECT which flex missed.
 */
#define REJECT reject_used_but_not_detected
#define yymore() yymore_used_but_not_detected
#define YY_MORE_ADJ 0
#define YY_RESTORE_YY_MORE_OFFSET
char *yytext;
#line 1 "lang/lex.l"
#line 2 "lang/lex.l"
#ifndef _LEX_YY_C
#define _LEX_YY_C
#include <stdlib.h>
#include "parse.h"
#include "y.tab.h"
#include "string_proc.h"
// Add these declarations
int yycolumn = 1;
int yyprevcolumn = 1;
int yyprevlineno = 1;

long long int yyabsoluteoffset = 0; 
long long int yyprevoffset = 0; 


// 0x[0-9a-fA-F]{1,2}c     { 
//                           char temp[3] = {0}; // Max 2 hex digits + null terminator
//                           strncpy(temp, yytext + 2, yyleng - 3); // Skip "0x" and 'c'
//                           
//                           int value = (int)strtol(temp, NULL, 16);
//                           
//                           if(value > 255) {
//                               yyerror("Byte literal too large");
//                               fprintf(stderr, "Byte literal too large");
//                           }
// 
//                           yylval.vchar = (char)value;
//                           return TOK_CHAR;
//                         }

// This macro is called at the beginning of each rule's action
#define YY_USER_ACTION \
    yyprevlineno = yylineno; \
    yylloc.first_line = yylloc.last_line = yylineno; \
    yylloc.first_column = yycolumn; \
    yylloc.last_column = yycolumn + yyleng - 1; \
    yyprevcolumn = yycolumn; \
    yycolumn += yyleng; \
    yyprevoffset = yyabsoluteoffset; \
    yyabsoluteoffset += yyleng;
#line 707 "lang/lex.yy.c"

#line 709 "lang/lex.yy.c"

#define INITIAL 0
#define FSTRING 1
#define TRIPLE_FSTRING 2

#ifndef YY_NO_UNISTD_H
/* Special case for "unistd.h", since it is non-ANSI. We include it way
 * down here because we want the user's section 1 to have been scanned first.
 * The user has a chance to override it with an option.
 */
#include <unistd.h>
#endif

#ifndef YY_EXTRA_TYPE
#define YY_EXTRA_TYPE void *
#endif

static int yy_init_globals ( void );

/* Accessor methods to globals.
   These are made visible to non-reentrant scanners for convenience. */

int yylex_destroy ( void );

int yyget_debug ( void );

void yyset_debug ( int debug_flag  );

YY_EXTRA_TYPE yyget_extra ( void );

void yyset_extra ( YY_EXTRA_TYPE user_defined  );

FILE *yyget_in ( void );

void yyset_in  ( FILE * _in_str  );

FILE *yyget_out ( void );

void yyset_out  ( FILE * _out_str  );

			int yyget_leng ( void );

char *yyget_text ( void );

int yyget_lineno ( void );

void yyset_lineno ( int _line_number  );

/* Macros after this point can all be overridden by user definitions in
 * section 1.
 */

#ifndef YY_SKIP_YYWRAP
#ifdef __cplusplus
extern "C" int yywrap ( void );
#else
extern int yywrap ( void );
#endif
#endif

#ifndef YY_NO_UNPUT
    
    static void yyunput ( int c, char *buf_ptr  );
    
#endif

#ifndef yytext_ptr
static void yy_flex_strncpy ( char *, const char *, int );
#endif

#ifdef YY_NEED_STRLEN
static int yy_flex_strlen ( const char * );
#endif

#ifndef YY_NO_INPUT
#ifdef __cplusplus
static int yyinput ( void );
#else
static int input ( void );
#endif

#endif

/* Amount of stuff to slurp up with each read. */
#ifndef YY_READ_BUF_SIZE
#ifdef __ia64__
/* On IA-64, the buffer size is 16k, not 8k */
#define YY_READ_BUF_SIZE 16384
#else
#define YY_READ_BUF_SIZE 8192
#endif /* __ia64__ */
#endif

/* Copy whatever the last rule matched to the standard output. */
#ifndef ECHO
/* This used to be an fputs(), but since the string might contain NUL's,
 * we now use fwrite().
 */
#define ECHO do { if (fwrite( yytext, (size_t) yyleng, 1, yyout )) {} } while (0)
#endif

/* Gets input and stuffs it into "buf".  number of characters read, or YY_NULL,
 * is returned in "result".
 */
#ifndef YY_INPUT
#define YY_INPUT(buf,result,max_size) \
	if ( YY_CURRENT_BUFFER_LVALUE->yy_is_interactive ) \
		{ \
		int c = '*'; \
		int n; \
		for ( n = 0; n < max_size && \
			     (c = getc( yyin )) != EOF && c != '\n'; ++n ) \
			buf[n] = (char) c; \
		if ( c == '\n' ) \
			buf[n++] = (char) c; \
		if ( c == EOF && ferror( yyin ) ) \
			YY_FATAL_ERROR( "input in flex scanner failed" ); \
		result = n; \
		} \
	else \
		{ \
		errno=0; \
		while ( (result = (int) fread(buf, 1, (yy_size_t) max_size, yyin)) == 0 && ferror(yyin)) \
			{ \
			if( errno != EINTR) \
				{ \
				YY_FATAL_ERROR( "input in flex scanner failed" ); \
				break; \
				} \
			errno=0; \
			clearerr(yyin); \
			} \
		}\
\

#endif

/* No semi-colon after return; correct usage is to write "yyterminate();" -
 * we don't want an extra ';' after the "return" because that will cause
 * some compilers to complain about unreachable statements.
 */
#ifndef yyterminate
#define yyterminate() return YY_NULL
#endif

/* Number of entries by which start-condition stack grows. */
#ifndef YY_START_STACK_INCR
#define YY_START_STACK_INCR 25
#endif

/* Report a fatal error. */
#ifndef YY_FATAL_ERROR
#define YY_FATAL_ERROR(msg) yy_fatal_error( msg )
#endif

/* end tables serialization structures and prototypes */

/* Default declaration of generated scanner - a define so the user can
 * easily add parameters.
 */
#ifndef YY_DECL
#define YY_DECL_IS_OURS 1

extern int yylex (void);

#define YY_DECL int yylex (void)
#endif /* !YY_DECL */

/* Code executed at the beginning of each rule, after yytext and yyleng
 * have been set up.
 */
#ifndef YY_USER_ACTION
#define YY_USER_ACTION
#endif

/* Code executed at the end of each rule. */
#ifndef YY_BREAK
#define YY_BREAK /*LINTED*/break;
#endif

#define YY_RULE_SETUP \
	YY_USER_ACTION

/** The main scanner function which does all the work.
 */
YY_DECL
{
	yy_state_type yy_current_state;
	char *yy_cp, *yy_bp;
	int yy_act;
    
	if ( !(yy_init) )
		{
		(yy_init) = 1;

#ifdef YY_USER_INIT
		YY_USER_INIT;
#endif

		if ( ! (yy_start) )
			(yy_start) = 1;	/* first start state */

		if ( ! yyin )
			yyin = stdin;

		if ( ! yyout )
			yyout = stdout;

		if ( ! YY_CURRENT_BUFFER ) {
			yyensure_buffer_stack ();
			YY_CURRENT_BUFFER_LVALUE =
				yy_create_buffer( yyin, YY_BUF_SIZE );
		}

		yy_load_buffer_state(  );
		}

	{
#line 50 "lang/lex.l"

#line 930 "lang/lex.yy.c"

	while ( /*CONSTCOND*/1 )		/* loops until end-of-file is reached */
		{
		yy_cp = (yy_c_buf_p);

		/* Support of yytext. */
		*yy_cp = (yy_hold_char);

		/* yy_bp points to the position in yy_ch_buf of the start of
		 * the current run.
		 */
		yy_bp = yy_cp;

		yy_current_state = (yy_start);
yy_match:
		do
			{
			YY_CHAR yy_c = yy_ec[YY_SC_TO_UI(*yy_cp)] ;
			if ( yy_accept[yy_current_state] )
				{
				(yy_last_accepting_state) = yy_current_state;
				(yy_last_accepting_cpos) = yy_cp;
				}
			while ( yy_chk[yy_base[yy_current_state] + yy_c] != yy_current_state )
				{
				yy_current_state = (int) yy_def[yy_current_state];
				if ( yy_current_state >= 183 )
					yy_c = yy_meta[yy_c];
				}
			yy_current_state = yy_nxt[yy_base[yy_current_state] + yy_c];
			++yy_cp;
			}
		while ( yy_base[yy_current_state] != 550 );

yy_find_action:
		yy_act = yy_accept[yy_current_state];
		if ( yy_act == 0 )
			{ /* have to back up */
			yy_cp = (yy_last_accepting_cpos);
			yy_current_state = (yy_last_accepting_state);
			yy_act = yy_accept[yy_current_state];
			}

		YY_DO_BEFORE_ACTION;

		if ( yy_act != YY_END_OF_BUFFER && yy_rule_can_match_eol[yy_act] )
			{
			int yyl;
			for ( yyl = 0; yyl < yyleng; ++yyl )
				if ( yytext[yyl] == '\n' )
					
    yylineno++;
;
			}

do_action:	/* This label is used only to access EOF actions. */

		switch ( yy_act )
	{ /* beginning of action switch */
			case 0: /* must back up */
			/* undo the effects of YY_DO_BEFORE_ACTION */
			*yy_cp = (yy_hold_char);
			yy_cp = (yy_last_accepting_cpos);
			yy_current_state = (yy_last_accepting_state);
			goto yy_find_action;

case 1:
YY_RULE_SETUP
#line 51 "lang/lex.l"
return FN;
	YY_BREAK
case 2:
YY_RULE_SETUP
#line 52 "lang/lex.l"
return LET;
	YY_BREAK
case 3:
YY_RULE_SETUP
#line 53 "lang/lex.l"
return IN;
	YY_BREAK
case 4:
YY_RULE_SETUP
#line 54 "lang/lex.l"
return AND;
	YY_BREAK
case 5:
YY_RULE_SETUP
#line 55 "lang/lex.l"
return TOK_VOID;
	YY_BREAK
case 6:
YY_RULE_SETUP
#line 56 "lang/lex.l"
return EXTERN;
	YY_BREAK
case 7:
YY_RULE_SETUP
#line 57 "lang/lex.l"
return TRUE;
	YY_BREAK
case 8:
YY_RULE_SETUP
#line 58 "lang/lex.l"
return FALSE;
	YY_BREAK
case 9:
YY_RULE_SETUP
#line 59 "lang/lex.l"
return TRIPLE_DOT;
	YY_BREAK
case 10:
YY_RULE_SETUP
#line 60 "lang/lex.l"
return MATCH;
	YY_BREAK
case 11:
YY_RULE_SETUP
#line 61 "lang/lex.l"
return WITH;
	YY_BREAK
case 12:
YY_RULE_SETUP
#line 62 "lang/lex.l"
return *yytext;
	YY_BREAK
case 13:
YY_RULE_SETUP
#line 63 "lang/lex.l"
return *yytext;
	YY_BREAK
case 14:
YY_RULE_SETUP
#line 64 "lang/lex.l"
return IMPORT;
	YY_BREAK
case 15:
YY_RULE_SETUP
#line 65 "lang/lex.l"
return OPEN;
	YY_BREAK
case 16:
YY_RULE_SETUP
#line 66 "lang/lex.l"
return *yytext;
	YY_BREAK
case 17:
YY_RULE_SETUP
#line 67 "lang/lex.l"
return TYPE;
	YY_BREAK
case 18:
YY_RULE_SETUP
#line 68 "lang/lex.l"
return TEST_ID;
	YY_BREAK
case 19:
YY_RULE_SETUP
#line 69 "lang/lex.l"
return *yytext;
	YY_BREAK
case 20:
YY_RULE_SETUP
#line 70 "lang/lex.l"
return *yytext;
	YY_BREAK
case 21:
YY_RULE_SETUP
#line 71 "lang/lex.l"
return THEN;
	YY_BREAK
case 22:
YY_RULE_SETUP
#line 72 "lang/lex.l"
return ELSE;
	YY_BREAK
case 23:
YY_RULE_SETUP
#line 73 "lang/lex.l"
return *yytext;
	YY_BREAK
case 24:
YY_RULE_SETUP
#line 74 "lang/lex.l"
return DOUBLE_AMP;
	YY_BREAK
case 25:
YY_RULE_SETUP
#line 75 "lang/lex.l"
return AMPERSAND;
	YY_BREAK
case 26:
YY_RULE_SETUP
#line 76 "lang/lex.l"
return DOUBLE_PIPE;
	YY_BREAK
case 27:
YY_RULE_SETUP
#line 77 "lang/lex.l"
return *yytext;
	YY_BREAK
case 28:
YY_RULE_SETUP
#line 78 "lang/lex.l"
return THUNK;
	YY_BREAK
case 29:
YY_RULE_SETUP
#line 79 "lang/lex.l"
return *yytext;
	YY_BREAK
case 30:
YY_RULE_SETUP
#line 80 "lang/lex.l"
return *yytext;
	YY_BREAK
case 31:
YY_RULE_SETUP
#line 81 "lang/lex.l"
return *yytext;
	YY_BREAK
case 32:
YY_RULE_SETUP
#line 82 "lang/lex.l"
{

                          int len = yyleng;
                          yylval.vident.chars = strdup(yytext); 
                          yylval.vident.length = len;
                          yylval.vident.hash = hash_string(yylval.vident.chars, len);
                          return IDENTIFIER;
                        }
	YY_BREAK
case 33:
YY_RULE_SETUP
#line 91 "lang/lex.l"
{

                          int len = yyleng;
                          yylval.vident.chars = strdup(yytext); 
                          yylval.vident.length = len;
                          yylval.vident.hash = hash_string(yylval.vident.chars, len);
                          return MACRO_IDENTIFIER;
                        }
	YY_BREAK
case 34:
YY_RULE_SETUP
#line 100 "lang/lex.l"
{
                          int len = yyleng;
                          yylval.vident.chars = strdup(yytext); 
                          yylval.vident.length = len;
                          yylval.vident.hash = hash_string(yylval.vident.chars, len);
                          return PATH_IDENTIFIER;
                        }
	YY_BREAK
case 35:
YY_RULE_SETUP
#line 108 "lang/lex.l"
{

                          int len = yyleng;
                          yylval.vident.chars = strdup(yytext); 
                          yylval.vident.chars[yyleng-1] = 0;
                          yylval.vident.chars[yyleng-2] = 0;
                          yylval.vident.length = len;
                          yylval.vident.hash = hash_string(yylval.vident.chars, len);
                          return IDENTIFIER_LIST;
                        }
	YY_BREAK
case 36:
YY_RULE_SETUP
#line 119 "lang/lex.l"
return *yytext;
	YY_BREAK
case 37:
YY_RULE_SETUP
#line 122 "lang/lex.l"
{ BEGIN(FSTRING); return FSTRING_START; }
	YY_BREAK
case 38:
YY_RULE_SETUP
#line 123 "lang/lex.l"
{ BEGIN(INITIAL); return FSTRING_END; }
	YY_BREAK
case 39:
YY_RULE_SETUP
#line 124 "lang/lex.l"
{ 
                          // Escaped opening brace - treat as literal text
                          yylval.vstr.chars = strdup("{");
                          yylval.vstr.length = 1;
                          yylval.vstr.hash = hash_string("{", 1);
                          return FSTRING_TEXT;
                        }
	YY_BREAK
case 40:
YY_RULE_SETUP
#line 131 "lang/lex.l"
{ 
                          // Escaped closing brace - treat as literal text
                          yylval.vstr.chars = strdup("}");
                          yylval.vstr.length = 1;
                          yylval.vstr.hash = hash_string("}", 1);
                          return FSTRING_TEXT;
                        }
	YY_BREAK
case 41:
YY_RULE_SETUP
#line 138 "lang/lex.l"
{ BEGIN(INITIAL); return FSTRING_INTERP_START; }
	YY_BREAK
case 42:
/* rule 42 can match eol */
YY_RULE_SETUP
#line 139 "lang/lex.l"
{ 
                          int len = yyleng;
                          char *raw_str = strndup(yytext, len);
                          char *processed_str = process_escapes(raw_str, len);
                          free(raw_str);
                          yylval.vstr.chars = processed_str;
                          yylval.vstr.length = strlen(processed_str);
                          yylval.vstr.hash = hash_string(processed_str, yylval.vstr.length);
                          return FSTRING_TEXT;
                        }
	YY_BREAK
case 43:
/* rule 43 can match eol */
YY_RULE_SETUP
#line 149 "lang/lex.l"
{
                          // Handle other escape sequences in f-strings
                          int len = yyleng;
                          char *raw_str = strndup(yytext, len);
                          char *processed_str = process_escapes(raw_str, len);
                          free(raw_str);
                          yylval.vstr.chars = processed_str;
                          yylval.vstr.length = strlen(processed_str);
                          yylval.vstr.hash = hash_string(processed_str, yylval.vstr.length);
                          return FSTRING_TEXT;
                        }
	YY_BREAK
case 44:
YY_RULE_SETUP
#line 162 "lang/lex.l"
{ BEGIN(TRIPLE_FSTRING); return FSTRING_START; }
	YY_BREAK
case 45:
YY_RULE_SETUP
#line 163 "lang/lex.l"
{ BEGIN(INITIAL); return FSTRING_END; }
	YY_BREAK
case 46:
YY_RULE_SETUP
#line 164 "lang/lex.l"
{ BEGIN(INITIAL); return FSTRING_INTERP_START; }
	YY_BREAK
case 47:
/* rule 47 can match eol */
YY_RULE_SETUP
#line 165 "lang/lex.l"
{ 
                          int len = yyleng;
                          char *raw_str = strndup(yytext, len);
                          // Trim first and last newline if present

                          if (raw_str[0] == '\n') {
                            raw_str++;
                            len--;
                          }
                          if (len > 0 && raw_str[len-1] == '\n') {
                            raw_str[len-1] = '\0';
                            len--;
                          }
                          char *processed_str = process_escapes(raw_str, len);
                          yylval.vstr.chars = processed_str;
                          yylval.vstr.length = strlen(processed_str);
                          yylval.vstr.hash = hash_string(processed_str, yylval.vstr.length);
                          return FSTRING_TEXT;
                        }
	YY_BREAK
case 48:
YY_RULE_SETUP
#line 184 "lang/lex.l"
{ 
                          if (YYSTATE == FSTRING) {
                            return FSTRING_INTERP_END;
                          } else {
                            BEGIN(FSTRING); 
                            return FSTRING_INTERP_END;
                          }
                        }
	YY_BREAK
case 49:
YY_RULE_SETUP
#line 193 "lang/lex.l"
{
                          int len = yyleng - 2;
                          char *raw_str = strndup(yytext + 1, len); // remove surrounding " chars
                          char *processed_str = process_escapes(raw_str, len); // process escape sequences
                          free(raw_str);
                          yylval.vstr.chars = processed_str;
                          yylval.vstr.length = strlen(processed_str);
                          yylval.vstr.hash = hash_string(processed_str, yylval.vstr.length);
                          return TOK_STRING;
                        }
	YY_BREAK
case 50:
YY_RULE_SETUP
#line 205 "lang/lex.l"
{ 
                          yylval.vint = atoi(yytext);
                          return INTEGER;
                        }
	YY_BREAK
case 51:
YY_RULE_SETUP
#line 210 "lang/lex.l"
{ 
                          yylval.vdouble = atof(yytext);
                          return DOUBLE;
                        }
	YY_BREAK
case 52:
YY_RULE_SETUP
#line 214 "lang/lex.l"
{ 
                          yylval.vint = atoi(yytext);
                          return INTEGER;
                        }
	YY_BREAK
case 53:
YY_RULE_SETUP
#line 219 "lang/lex.l"
{ 
                          // hexadecimal int
                          yylval.vint = (int)strtol(yytext, NULL, 16);
                          return TOK_CHAR;
                        }
	YY_BREAK
case 54:
YY_RULE_SETUP
#line 225 "lang/lex.l"
{
                        yylval.vdouble = atof(yytext);
                        return DOUBLE;
                        }
	YY_BREAK
case 55:
YY_RULE_SETUP
#line 230 "lang/lex.l"
return PIPE;
	YY_BREAK
case 56:
YY_RULE_SETUP
#line 231 "lang/lex.l"
return DOUBLE_AT;
	YY_BREAK
case 57:
YY_RULE_SETUP
#line 233 "lang/lex.l"
{
                          /*printf("operator '%s'", yytext);*/
                          return *yytext;
                        }
	YY_BREAK
case 58:
YY_RULE_SETUP
#line 238 "lang/lex.l"
return MODULO;
	YY_BREAK
case 59:
YY_RULE_SETUP
#line 239 "lang/lex.l"
return GE;
	YY_BREAK
case 60:
YY_RULE_SETUP
#line 240 "lang/lex.l"
return LE;
	YY_BREAK
case 61:
YY_RULE_SETUP
#line 241 "lang/lex.l"
return EQ;
	YY_BREAK
case 62:
YY_RULE_SETUP
#line 242 "lang/lex.l"
return NE;
	YY_BREAK
case 63:
YY_RULE_SETUP
#line 243 "lang/lex.l"
return DOUBLE_COLON;
	YY_BREAK
case 64:
YY_RULE_SETUP
#line 244 "lang/lex.l"
return *yytext;
	YY_BREAK
case 65:
YY_RULE_SETUP
#line 245 "lang/lex.l"
return ARROW;
	YY_BREAK
case 66:
YY_RULE_SETUP
#line 246 "lang/lex.l"
return *yytext;
	YY_BREAK
case 67:
YY_RULE_SETUP
#line 247 "lang/lex.l"
;       /* ignore comments starting with # */
	YY_BREAK
case 68:
YY_RULE_SETUP
#line 250 "lang/lex.l"
;       /* ignore whitespace */
	YY_BREAK
case 69:
/* rule 69 can match eol */
YY_RULE_SETUP
#line 251 "lang/lex.l"
{ yycolumn = 1; }      
	YY_BREAK
case 70:
YY_RULE_SETUP
#line 253 "lang/lex.l"
{ yylval.vchar = '\n'; return TOK_CHAR; }
	YY_BREAK
case 71:
YY_RULE_SETUP
#line 254 "lang/lex.l"
{ yylval.vchar = '\t'; return TOK_CHAR; }
	YY_BREAK
case 72:
YY_RULE_SETUP
#line 255 "lang/lex.l"
{ yylval.vchar = '\''; return TOK_CHAR; }
	YY_BREAK
case 73:
YY_RULE_SETUP
#line 256 "lang/lex.l"
{ yylval.vchar = '\0'; return TOK_CHAR; }
	YY_BREAK
case 74:
YY_RULE_SETUP
#line 258 "lang/lex.l"
{ 
                    /* Matched a character literal */
                    /* You might want to return a token here, e.g., return CHAR_LITERAL; */
                    yylval.vchar = *(yytext + 1);
                    return TOK_CHAR;
                }
	YY_BREAK
case 75:
YY_RULE_SETUP
#line 265 "lang/lex.l"
{
                    // special identifiers for declaring binops
                    int len = yyleng;
                    yylval.vident.chars = strdup(yytext); 
                    yylval.vident.length = len;
                    yylval.vident.hash = hash_string(yylval.vident.chars, len);
                    return IDENTIFIER;
                }
	YY_BREAK
case 76:
YY_RULE_SETUP
#line 274 "lang/lex.l"
{ char err[64]; snprintf(err, sizeof(err), "Unknown character: %s", yytext); yyerror(err); }
	YY_BREAK
case 77:
YY_RULE_SETUP
#line 275 "lang/lex.l"
ECHO;
	YY_BREAK
#line 1511 "lang/lex.yy.c"
case YY_STATE_EOF(INITIAL):
case YY_STATE_EOF(FSTRING):
case YY_STATE_EOF(TRIPLE_FSTRING):
	yyterminate();

	case YY_END_OF_BUFFER:
		{
		/* Amount of text matched not including the EOB char. */
		int yy_amount_of_matched_text = (int) (yy_cp - (yytext_ptr)) - 1;

		/* Undo the effects of YY_DO_BEFORE_ACTION. */
		*yy_cp = (yy_hold_char);
		YY_RESTORE_YY_MORE_OFFSET

		if ( YY_CURRENT_BUFFER_LVALUE->yy_buffer_status == YY_BUFFER_NEW )
			{
			/* We're scanning a new file or input source.  It's
			 * possible that this happened because the user
			 * just pointed yyin at a new source and called
			 * yylex().  If so, then we have to assure
			 * consistency between YY_CURRENT_BUFFER and our
			 * globals.  Here is the right place to do so, because
			 * this is the first action (other than possibly a
			 * back-up) that will match for the new input source.
			 */
			(yy_n_chars) = YY_CURRENT_BUFFER_LVALUE->yy_n_chars;
			YY_CURRENT_BUFFER_LVALUE->yy_input_file = yyin;
			YY_CURRENT_BUFFER_LVALUE->yy_buffer_status = YY_BUFFER_NORMAL;
			}

		/* Note that here we test for yy_c_buf_p "<=" to the position
		 * of the first EOB in the buffer, since yy_c_buf_p will
		 * already have been incremented past the NUL character
		 * (since all states make transitions on EOB to the
		 * end-of-buffer state).  Contrast this with the test
		 * in input().
		 */
		if ( (yy_c_buf_p) <= &YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[(yy_n_chars)] )
			{ /* This was really a NUL. */
			yy_state_type yy_next_state;

			(yy_c_buf_p) = (yytext_ptr) + yy_amount_of_matched_text;

			yy_current_state = yy_get_previous_state(  );

			/* Okay, we're now positioned to make the NUL
			 * transition.  We couldn't have
			 * yy_get_previous_state() go ahead and do it
			 * for us because it doesn't know how to deal
			 * with the possibility of jamming (and we don't
			 * want to build jamming into it because then it
			 * will run more slowly).
			 */

			yy_next_state = yy_try_NUL_trans( yy_current_state );

			yy_bp = (yytext_ptr) + YY_MORE_ADJ;

			if ( yy_next_state )
				{
				/* Consume the NUL. */
				yy_cp = ++(yy_c_buf_p);
				yy_current_state = yy_next_state;
				goto yy_match;
				}

			else
				{
				yy_cp = (yy_c_buf_p);
				goto yy_find_action;
				}
			}

		else switch ( yy_get_next_buffer(  ) )
			{
			case EOB_ACT_END_OF_FILE:
				{
				(yy_did_buffer_switch_on_eof) = 0;

				if ( yywrap(  ) )
					{
					/* Note: because we've taken care in
					 * yy_get_next_buffer() to have set up
					 * yytext, we can now set up
					 * yy_c_buf_p so that if some total
					 * hoser (like flex itself) wants to
					 * call the scanner after we return the
					 * YY_NULL, it'll still work - another
					 * YY_NULL will get returned.
					 */
					(yy_c_buf_p) = (yytext_ptr) + YY_MORE_ADJ;

					yy_act = YY_STATE_EOF(YY_START);
					goto do_action;
					}

				else
					{
					if ( ! (yy_did_buffer_switch_on_eof) )
						YY_NEW_FILE;
					}
				break;
				}

			case EOB_ACT_CONTINUE_SCAN:
				(yy_c_buf_p) =
					(yytext_ptr) + yy_amount_of_matched_text;

				yy_current_state = yy_get_previous_state(  );

				yy_cp = (yy_c_buf_p);
				yy_bp = (yytext_ptr) + YY_MORE_ADJ;
				goto yy_match;

			case EOB_ACT_LAST_MATCH:
				(yy_c_buf_p) =
				&YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[(yy_n_chars)];

				yy_current_state = yy_get_previous_state(  );

				yy_cp = (yy_c_buf_p);
				yy_bp = (yytext_ptr) + YY_MORE_ADJ;
				goto yy_find_action;
			}
		break;
		}

	default:
		YY_FATAL_ERROR(
			"fatal flex scanner internal error--no action found" );
	} /* end of action switch */
		} /* end of scanning one token */
	} /* end of user's declarations */
} /* end of yylex */

/* yy_get_next_buffer - try to read in a new buffer
 *
 * Returns a code representing an action:
 *	EOB_ACT_LAST_MATCH -
 *	EOB_ACT_CONTINUE_SCAN - continue scanning from current position
 *	EOB_ACT_END_OF_FILE - end of file
 */
static int yy_get_next_buffer (void)
{
    	char *dest = YY_CURRENT_BUFFER_LVALUE->yy_ch_buf;
	char *source = (yytext_ptr);
	int number_to_move, i;
	int ret_val;

	if ( (yy_c_buf_p) > &YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[(yy_n_chars) + 1] )
		YY_FATAL_ERROR(
		"fatal flex scanner internal error--end of buffer missed" );

	if ( YY_CURRENT_BUFFER_LVALUE->yy_fill_buffer == 0 )
		{ /* Don't try to fill the buffer, so this is an EOF. */
		if ( (yy_c_buf_p) - (yytext_ptr) - YY_MORE_ADJ == 1 )
			{
			/* We matched a single character, the EOB, so
			 * treat this as a final EOF.
			 */
			return EOB_ACT_END_OF_FILE;
			}

		else
			{
			/* We matched some text prior to the EOB, first
			 * process it.
			 */
			return EOB_ACT_LAST_MATCH;
			}
		}

	/* Try to read more data. */

	/* First move last chars to start of buffer. */
	number_to_move = (int) ((yy_c_buf_p) - (yytext_ptr) - 1);

	for ( i = 0; i < number_to_move; ++i )
		*(dest++) = *(source++);

	if ( YY_CURRENT_BUFFER_LVALUE->yy_buffer_status == YY_BUFFER_EOF_PENDING )
		/* don't do the read, it's not guaranteed to return an EOF,
		 * just force an EOF
		 */
		YY_CURRENT_BUFFER_LVALUE->yy_n_chars = (yy_n_chars) = 0;

	else
		{
			int num_to_read =
			YY_CURRENT_BUFFER_LVALUE->yy_buf_size - number_to_move - 1;

		while ( num_to_read <= 0 )
			{ /* Not enough room in the buffer - grow it. */

			/* just a shorter name for the current buffer */
			YY_BUFFER_STATE b = YY_CURRENT_BUFFER_LVALUE;

			int yy_c_buf_p_offset =
				(int) ((yy_c_buf_p) - b->yy_ch_buf);

			if ( b->yy_is_our_buffer )
				{
				int new_size = b->yy_buf_size * 2;

				if ( new_size <= 0 )
					b->yy_buf_size += b->yy_buf_size / 8;
				else
					b->yy_buf_size *= 2;

				b->yy_ch_buf = (char *)
					/* Include room in for 2 EOB chars. */
					yyrealloc( (void *) b->yy_ch_buf,
							 (yy_size_t) (b->yy_buf_size + 2)  );
				}
			else
				/* Can't grow it, we don't own it. */
				b->yy_ch_buf = NULL;

			if ( ! b->yy_ch_buf )
				YY_FATAL_ERROR(
				"fatal error - scanner input buffer overflow" );

			(yy_c_buf_p) = &b->yy_ch_buf[yy_c_buf_p_offset];

			num_to_read = YY_CURRENT_BUFFER_LVALUE->yy_buf_size -
						number_to_move - 1;

			}

		if ( num_to_read > YY_READ_BUF_SIZE )
			num_to_read = YY_READ_BUF_SIZE;

		/* Read in more data. */
		YY_INPUT( (&YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[number_to_move]),
			(yy_n_chars), num_to_read );

		YY_CURRENT_BUFFER_LVALUE->yy_n_chars = (yy_n_chars);
		}

	if ( (yy_n_chars) == 0 )
		{
		if ( number_to_move == YY_MORE_ADJ )
			{
			ret_val = EOB_ACT_END_OF_FILE;
			yyrestart( yyin  );
			}

		else
			{
			ret_val = EOB_ACT_LAST_MATCH;
			YY_CURRENT_BUFFER_LVALUE->yy_buffer_status =
				YY_BUFFER_EOF_PENDING;
			}
		}

	else
		ret_val = EOB_ACT_CONTINUE_SCAN;

	if (((yy_n_chars) + number_to_move) > YY_CURRENT_BUFFER_LVALUE->yy_buf_size) {
		/* Extend the array by 50%, plus the number we really need. */
		int new_size = (yy_n_chars) + number_to_move + ((yy_n_chars) >> 1);
		YY_CURRENT_BUFFER_LVALUE->yy_ch_buf = (char *) yyrealloc(
			(void *) YY_CURRENT_BUFFER_LVALUE->yy_ch_buf, (yy_size_t) new_size  );
		if ( ! YY_CURRENT_BUFFER_LVALUE->yy_ch_buf )
			YY_FATAL_ERROR( "out of dynamic memory in yy_get_next_buffer()" );
		/* "- 2" to take care of EOB's */
		YY_CURRENT_BUFFER_LVALUE->yy_buf_size = (int) (new_size - 2);
	}

	(yy_n_chars) += number_to_move;
	YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[(yy_n_chars)] = YY_END_OF_BUFFER_CHAR;
	YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[(yy_n_chars) + 1] = YY_END_OF_BUFFER_CHAR;

	(yytext_ptr) = &YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[0];

	return ret_val;
}

/* yy_get_previous_state - get the state just before the EOB char was reached */

    static yy_state_type yy_get_previous_state (void)
{
	yy_state_type yy_current_state;
	char *yy_cp;
    
	yy_current_state = (yy_start);

	for ( yy_cp = (yytext_ptr) + YY_MORE_ADJ; yy_cp < (yy_c_buf_p); ++yy_cp )
		{
		YY_CHAR yy_c = (*yy_cp ? yy_ec[YY_SC_TO_UI(*yy_cp)] : 1);
		if ( yy_accept[yy_current_state] )
			{
			(yy_last_accepting_state) = yy_current_state;
			(yy_last_accepting_cpos) = yy_cp;
			}
		while ( yy_chk[yy_base[yy_current_state] + yy_c] != yy_current_state )
			{
			yy_current_state = (int) yy_def[yy_current_state];
			if ( yy_current_state >= 183 )
				yy_c = yy_meta[yy_c];
			}
		yy_current_state = yy_nxt[yy_base[yy_current_state] + yy_c];
		}

	return yy_current_state;
}

/* yy_try_NUL_trans - try to make a transition on the NUL character
 *
 * synopsis
 *	next_state = yy_try_NUL_trans( current_state );
 */
    static yy_state_type yy_try_NUL_trans  (yy_state_type yy_current_state )
{
	int yy_is_jam;
    	char *yy_cp = (yy_c_buf_p);

	YY_CHAR yy_c = 1;
	if ( yy_accept[yy_current_state] )
		{
		(yy_last_accepting_state) = yy_current_state;
		(yy_last_accepting_cpos) = yy_cp;
		}
	while ( yy_chk[yy_base[yy_current_state] + yy_c] != yy_current_state )
		{
		yy_current_state = (int) yy_def[yy_current_state];
		if ( yy_current_state >= 183 )
			yy_c = yy_meta[yy_c];
		}
	yy_current_state = yy_nxt[yy_base[yy_current_state] + yy_c];
	yy_is_jam = (yy_current_state == 182);

		return yy_is_jam ? 0 : yy_current_state;
}

#ifndef YY_NO_UNPUT

    static void yyunput (int c, char * yy_bp )
{
	char *yy_cp;
    
    yy_cp = (yy_c_buf_p);

	/* undo effects of setting up yytext */
	*yy_cp = (yy_hold_char);

	if ( yy_cp < YY_CURRENT_BUFFER_LVALUE->yy_ch_buf + 2 )
		{ /* need to shift things up to make room */
		/* +2 for EOB chars. */
		int number_to_move = (yy_n_chars) + 2;
		char *dest = &YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[
					YY_CURRENT_BUFFER_LVALUE->yy_buf_size + 2];
		char *source =
				&YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[number_to_move];

		while ( source > YY_CURRENT_BUFFER_LVALUE->yy_ch_buf )
			*--dest = *--source;

		yy_cp += (int) (dest - source);
		yy_bp += (int) (dest - source);
		YY_CURRENT_BUFFER_LVALUE->yy_n_chars =
			(yy_n_chars) = (int) YY_CURRENT_BUFFER_LVALUE->yy_buf_size;

		if ( yy_cp < YY_CURRENT_BUFFER_LVALUE->yy_ch_buf + 2 )
			YY_FATAL_ERROR( "flex scanner push-back overflow" );
		}

	*--yy_cp = (char) c;

    if ( c == '\n' ){
        --yylineno;
    }

	(yytext_ptr) = yy_bp;
	(yy_hold_char) = *yy_cp;
	(yy_c_buf_p) = yy_cp;
}

#endif

#ifndef YY_NO_INPUT
#ifdef __cplusplus
    static int yyinput (void)
#else
    static int input  (void)
#endif

{
	int c;
    
	*(yy_c_buf_p) = (yy_hold_char);

	if ( *(yy_c_buf_p) == YY_END_OF_BUFFER_CHAR )
		{
		/* yy_c_buf_p now points to the character we want to return.
		 * If this occurs *before* the EOB characters, then it's a
		 * valid NUL; if not, then we've hit the end of the buffer.
		 */
		if ( (yy_c_buf_p) < &YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[(yy_n_chars)] )
			/* This was really a NUL. */
			*(yy_c_buf_p) = '\0';

		else
			{ /* need more input */
			int offset = (int) ((yy_c_buf_p) - (yytext_ptr));
			++(yy_c_buf_p);

			switch ( yy_get_next_buffer(  ) )
				{
				case EOB_ACT_LAST_MATCH:
					/* This happens because yy_g_n_b()
					 * sees that we've accumulated a
					 * token and flags that we need to
					 * try matching the token before
					 * proceeding.  But for input(),
					 * there's no matching to consider.
					 * So convert the EOB_ACT_LAST_MATCH
					 * to EOB_ACT_END_OF_FILE.
					 */

					/* Reset buffer status. */
					yyrestart( yyin );

					/*FALLTHROUGH*/

				case EOB_ACT_END_OF_FILE:
					{
					if ( yywrap(  ) )
						return 0;

					if ( ! (yy_did_buffer_switch_on_eof) )
						YY_NEW_FILE;
#ifdef __cplusplus
					return yyinput();
#else
					return input();
#endif
					}

				case EOB_ACT_CONTINUE_SCAN:
					(yy_c_buf_p) = (yytext_ptr) + offset;
					break;
				}
			}
		}

	c = *(unsigned char *) (yy_c_buf_p);	/* cast for 8-bit char's */
	*(yy_c_buf_p) = '\0';	/* preserve yytext */
	(yy_hold_char) = *++(yy_c_buf_p);

	if ( c == '\n' )
		
    yylineno++;
;

	return c;
}
#endif	/* ifndef YY_NO_INPUT */

/** Immediately switch to a different input stream.
 * @param input_file A readable stream.
 * 
 * @note This function does not reset the start condition to @c INITIAL .
 */
    void yyrestart  (FILE * input_file )
{
    
	if ( ! YY_CURRENT_BUFFER ){
        yyensure_buffer_stack ();
		YY_CURRENT_BUFFER_LVALUE =
            yy_create_buffer( yyin, YY_BUF_SIZE );
	}

	yy_init_buffer( YY_CURRENT_BUFFER, input_file );
	yy_load_buffer_state(  );
}

/** Switch to a different input buffer.
 * @param new_buffer The new input buffer.
 * 
 */
    void yy_switch_to_buffer  (YY_BUFFER_STATE  new_buffer )
{
    
	/* TODO. We should be able to replace this entire function body
	 * with
	 *		yypop_buffer_state();
	 *		yypush_buffer_state(new_buffer);
     */
	yyensure_buffer_stack ();
	if ( YY_CURRENT_BUFFER == new_buffer )
		return;

	if ( YY_CURRENT_BUFFER )
		{
		/* Flush out information for old buffer. */
		*(yy_c_buf_p) = (yy_hold_char);
		YY_CURRENT_BUFFER_LVALUE->yy_buf_pos = (yy_c_buf_p);
		YY_CURRENT_BUFFER_LVALUE->yy_n_chars = (yy_n_chars);
		}

	YY_CURRENT_BUFFER_LVALUE = new_buffer;
	yy_load_buffer_state(  );

	/* We don't actually know whether we did this switch during
	 * EOF (yywrap()) processing, but the only time this flag
	 * is looked at is after yywrap() is called, so it's safe
	 * to go ahead and always set it.
	 */
	(yy_did_buffer_switch_on_eof) = 1;
}

static void yy_load_buffer_state  (void)
{
    	(yy_n_chars) = YY_CURRENT_BUFFER_LVALUE->yy_n_chars;
	(yytext_ptr) = (yy_c_buf_p) = YY_CURRENT_BUFFER_LVALUE->yy_buf_pos;
	yyin = YY_CURRENT_BUFFER_LVALUE->yy_input_file;
	(yy_hold_char) = *(yy_c_buf_p);
}

/** Allocate and initialize an input buffer state.
 * @param file A readable stream.
 * @param size The character buffer size in bytes. When in doubt, use @c YY_BUF_SIZE.
 * 
 * @return the allocated buffer state.
 */
    YY_BUFFER_STATE yy_create_buffer  (FILE * file, int  size )
{
	YY_BUFFER_STATE b;
    
	b = (YY_BUFFER_STATE) yyalloc( sizeof( struct yy_buffer_state )  );
	if ( ! b )
		YY_FATAL_ERROR( "out of dynamic memory in yy_create_buffer()" );

	b->yy_buf_size = size;

	/* yy_ch_buf has to be 2 characters longer than the size given because
	 * we need to put in 2 end-of-buffer characters.
	 */
	b->yy_ch_buf = (char *) yyalloc( (yy_size_t) (b->yy_buf_size + 2)  );
	if ( ! b->yy_ch_buf )
		YY_FATAL_ERROR( "out of dynamic memory in yy_create_buffer()" );

	b->yy_is_our_buffer = 1;

	yy_init_buffer( b, file );

	return b;
}

/** Destroy the buffer.
 * @param b a buffer created with yy_create_buffer()
 * 
 */
    void yy_delete_buffer (YY_BUFFER_STATE  b )
{
    
	if ( ! b )
		return;

	if ( b == YY_CURRENT_BUFFER ) /* Not sure if we should pop here. */
		YY_CURRENT_BUFFER_LVALUE = (YY_BUFFER_STATE) 0;

	if ( b->yy_is_our_buffer )
		yyfree( (void *) b->yy_ch_buf  );

	yyfree( (void *) b  );
}

/* Initializes or reinitializes a buffer.
 * This function is sometimes called more than once on the same buffer,
 * such as during a yyrestart() or at EOF.
 */
    static void yy_init_buffer  (YY_BUFFER_STATE  b, FILE * file )

{
	int oerrno = errno;
    
	yy_flush_buffer( b );

	b->yy_input_file = file;
	b->yy_fill_buffer = 1;

    /* If b is the current buffer, then yy_init_buffer was _probably_
     * called from yyrestart() or through yy_get_next_buffer.
     * In that case, we don't want to reset the lineno or column.
     */
    if (b != YY_CURRENT_BUFFER){
        b->yy_bs_lineno = 1;
        b->yy_bs_column = 0;
    }

        b->yy_is_interactive = file ? (isatty( fileno(file) ) > 0) : 0;
    
	errno = oerrno;
}

/** Discard all buffered characters. On the next scan, YY_INPUT will be called.
 * @param b the buffer state to be flushed, usually @c YY_CURRENT_BUFFER.
 * 
 */
    void yy_flush_buffer (YY_BUFFER_STATE  b )
{
    	if ( ! b )
		return;

	b->yy_n_chars = 0;

	/* We always need two end-of-buffer characters.  The first causes
	 * a transition to the end-of-buffer state.  The second causes
	 * a jam in that state.
	 */
	b->yy_ch_buf[0] = YY_END_OF_BUFFER_CHAR;
	b->yy_ch_buf[1] = YY_END_OF_BUFFER_CHAR;

	b->yy_buf_pos = &b->yy_ch_buf[0];

	b->yy_at_bol = 1;
	b->yy_buffer_status = YY_BUFFER_NEW;

	if ( b == YY_CURRENT_BUFFER )
		yy_load_buffer_state(  );
}

/** Pushes the new state onto the stack. The new state becomes
 *  the current state. This function will allocate the stack
 *  if necessary.
 *  @param new_buffer The new state.
 *  
 */
void yypush_buffer_state (YY_BUFFER_STATE new_buffer )
{
    	if (new_buffer == NULL)
		return;

	yyensure_buffer_stack();

	/* This block is copied from yy_switch_to_buffer. */
	if ( YY_CURRENT_BUFFER )
		{
		/* Flush out information for old buffer. */
		*(yy_c_buf_p) = (yy_hold_char);
		YY_CURRENT_BUFFER_LVALUE->yy_buf_pos = (yy_c_buf_p);
		YY_CURRENT_BUFFER_LVALUE->yy_n_chars = (yy_n_chars);
		}

	/* Only push if top exists. Otherwise, replace top. */
	if (YY_CURRENT_BUFFER)
		(yy_buffer_stack_top)++;
	YY_CURRENT_BUFFER_LVALUE = new_buffer;

	/* copied from yy_switch_to_buffer. */
	yy_load_buffer_state(  );
	(yy_did_buffer_switch_on_eof) = 1;
}

/** Removes and deletes the top of the stack, if present.
 *  The next element becomes the new top.
 *  
 */
void yypop_buffer_state (void)
{
    	if (!YY_CURRENT_BUFFER)
		return;

	yy_delete_buffer(YY_CURRENT_BUFFER );
	YY_CURRENT_BUFFER_LVALUE = NULL;
	if ((yy_buffer_stack_top) > 0)
		--(yy_buffer_stack_top);

	if (YY_CURRENT_BUFFER) {
		yy_load_buffer_state(  );
		(yy_did_buffer_switch_on_eof) = 1;
	}
}

/* Allocates the stack if it does not exist.
 *  Guarantees space for at least one push.
 */
static void yyensure_buffer_stack (void)
{
	yy_size_t num_to_alloc;
    
	if (!(yy_buffer_stack)) {

		/* First allocation is just for 2 elements, since we don't know if this
		 * scanner will even need a stack. We use 2 instead of 1 to avoid an
		 * immediate realloc on the next call.
         */
      num_to_alloc = 1; /* After all that talk, this was set to 1 anyways... */
		(yy_buffer_stack) = (struct yy_buffer_state**)yyalloc
								(num_to_alloc * sizeof(struct yy_buffer_state*)
								);
		if ( ! (yy_buffer_stack) )
			YY_FATAL_ERROR( "out of dynamic memory in yyensure_buffer_stack()" );

		memset((yy_buffer_stack), 0, num_to_alloc * sizeof(struct yy_buffer_state*));

		(yy_buffer_stack_max) = num_to_alloc;
		(yy_buffer_stack_top) = 0;
		return;
	}

	if ((yy_buffer_stack_top) >= ((yy_buffer_stack_max)) - 1){

		/* Increase the buffer to prepare for a possible push. */
		yy_size_t grow_size = 8 /* arbitrary grow size */;

		num_to_alloc = (yy_buffer_stack_max) + grow_size;
		(yy_buffer_stack) = (struct yy_buffer_state**)yyrealloc
								((yy_buffer_stack),
								num_to_alloc * sizeof(struct yy_buffer_state*)
								);
		if ( ! (yy_buffer_stack) )
			YY_FATAL_ERROR( "out of dynamic memory in yyensure_buffer_stack()" );

		/* zero only the new slots.*/
		memset((yy_buffer_stack) + (yy_buffer_stack_max), 0, grow_size * sizeof(struct yy_buffer_state*));
		(yy_buffer_stack_max) = num_to_alloc;
	}
}

/** Setup the input buffer state to scan directly from a user-specified character buffer.
 * @param base the character buffer
 * @param size the size in bytes of the character buffer
 * 
 * @return the newly allocated buffer state object.
 */
YY_BUFFER_STATE yy_scan_buffer  (char * base, yy_size_t  size )
{
	YY_BUFFER_STATE b;
    
	if ( size < 2 ||
	     base[size-2] != YY_END_OF_BUFFER_CHAR ||
	     base[size-1] != YY_END_OF_BUFFER_CHAR )
		/* They forgot to leave room for the EOB's. */
		return NULL;

	b = (YY_BUFFER_STATE) yyalloc( sizeof( struct yy_buffer_state )  );
	if ( ! b )
		YY_FATAL_ERROR( "out of dynamic memory in yy_scan_buffer()" );

	b->yy_buf_size = (int) (size - 2);	/* "- 2" to take care of EOB's */
	b->yy_buf_pos = b->yy_ch_buf = base;
	b->yy_is_our_buffer = 0;
	b->yy_input_file = NULL;
	b->yy_n_chars = b->yy_buf_size;
	b->yy_is_interactive = 0;
	b->yy_at_bol = 1;
	b->yy_fill_buffer = 0;
	b->yy_buffer_status = YY_BUFFER_NEW;

	yy_switch_to_buffer( b  );

	return b;
}

/** Setup the input buffer state to scan a string. The next call to yylex() will
 * scan from a @e copy of @a str.
 * @param yystr a NUL-terminated string to scan
 * 
 * @return the newly allocated buffer state object.
 * @note If you want to scan bytes that may contain NUL values, then use
 *       yy_scan_bytes() instead.
 */
YY_BUFFER_STATE yy_scan_string (const char * yystr )
{
    
	return yy_scan_bytes( yystr, (int) strlen(yystr) );
}

/** Setup the input buffer state to scan the given bytes. The next call to yylex() will
 * scan from a @e copy of @a bytes.
 * @param yybytes the byte buffer to scan
 * @param _yybytes_len the number of bytes in the buffer pointed to by @a bytes.
 * 
 * @return the newly allocated buffer state object.
 */
YY_BUFFER_STATE yy_scan_bytes  (const char * yybytes, int  _yybytes_len )
{
	YY_BUFFER_STATE b;
	char *buf;
	yy_size_t n;
	int i;
    
	/* Get memory for full buffer, including space for trailing EOB's. */
	n = (yy_size_t) (_yybytes_len + 2);
	buf = (char *) yyalloc( n  );
	if ( ! buf )
		YY_FATAL_ERROR( "out of dynamic memory in yy_scan_bytes()" );

	for ( i = 0; i < _yybytes_len; ++i )
		buf[i] = yybytes[i];

	buf[_yybytes_len] = buf[_yybytes_len+1] = YY_END_OF_BUFFER_CHAR;

	b = yy_scan_buffer( buf, n );
	if ( ! b )
		YY_FATAL_ERROR( "bad buffer in yy_scan_bytes()" );

	/* It's okay to grow etc. this buffer, and we should throw it
	 * away when we're done.
	 */
	b->yy_is_our_buffer = 1;

	return b;
}

#ifndef YY_EXIT_FAILURE
#define YY_EXIT_FAILURE 2
#endif

static void yynoreturn yy_fatal_error (const char* msg )
{
			fprintf( stderr, "%s\n", msg );
	exit( YY_EXIT_FAILURE );
}

/* Redefine yyless() so it works in section 3 code. */

#undef yyless
#define yyless(n) \
	do \
		{ \
		/* Undo effects of setting up yytext. */ \
        int yyless_macro_arg = (n); \
        YY_LESS_LINENO(yyless_macro_arg);\
		yytext[yyleng] = (yy_hold_char); \
		(yy_c_buf_p) = yytext + yyless_macro_arg; \
		(yy_hold_char) = *(yy_c_buf_p); \
		*(yy_c_buf_p) = '\0'; \
		yyleng = yyless_macro_arg; \
		} \
	while ( 0 )

/* Accessor  methods (get/set functions) to struct members. */

/** Get the current line number.
 * 
 */
int yyget_lineno  (void)
{
    
    return yylineno;
}

/** Get the input stream.
 * 
 */
FILE *yyget_in  (void)
{
        return yyin;
}

/** Get the output stream.
 * 
 */
FILE *yyget_out  (void)
{
        return yyout;
}

/** Get the length of the current token.
 * 
 */
int yyget_leng  (void)
{
        return yyleng;
}

/** Get the current token.
 * 
 */

char *yyget_text  (void)
{
        return yytext;
}

/** Set the current line number.
 * @param _line_number line number
 * 
 */
void yyset_lineno (int  _line_number )
{
    
    yylineno = _line_number;
}

/** Set the input stream. This does not discard the current
 * input buffer.
 * @param _in_str A readable stream.
 * 
 * @see yy_switch_to_buffer
 */
void yyset_in (FILE *  _in_str )
{
        yyin = _in_str ;
}

void yyset_out (FILE *  _out_str )
{
        yyout = _out_str ;
}

int yyget_debug  (void)
{
        return yy_flex_debug;
}

void yyset_debug (int  _bdebug )
{
        yy_flex_debug = _bdebug ;
}

static int yy_init_globals (void)
{
        /* Initialization is the same as for the non-reentrant scanner.
     * This function is called from yylex_destroy(), so don't allocate here.
     */

    /* We do not touch yylineno unless the option is enabled. */
    yylineno =  1;
    
    (yy_buffer_stack) = NULL;
    (yy_buffer_stack_top) = 0;
    (yy_buffer_stack_max) = 0;
    (yy_c_buf_p) = NULL;
    (yy_init) = 0;
    (yy_start) = 0;

/* Defined in main.c */
#ifdef YY_STDINIT
    yyin = stdin;
    yyout = stdout;
#else
    yyin = NULL;
    yyout = NULL;
#endif

    /* For future reference: Set errno on error, since we are called by
     * yylex_init()
     */
    return 0;
}

/* yylex_destroy is for both reentrant and non-reentrant scanners. */
int yylex_destroy  (void)
{
    
    /* Pop the buffer stack, destroying each element. */
	while(YY_CURRENT_BUFFER){
		yy_delete_buffer( YY_CURRENT_BUFFER  );
		YY_CURRENT_BUFFER_LVALUE = NULL;
		yypop_buffer_state();
	}

	/* Destroy the stack itself. */
	yyfree((yy_buffer_stack) );
	(yy_buffer_stack) = NULL;

    /* Reset the globals. This is important in a non-reentrant scanner so the next time
     * yylex() is called, initialization will occur. */
    yy_init_globals( );

    return 0;
}

/*
 * Internal utility routines.
 */

#ifndef yytext_ptr
static void yy_flex_strncpy (char* s1, const char * s2, int n )
{
		
	int i;
	for ( i = 0; i < n; ++i )
		s1[i] = s2[i];
}
#endif

#ifdef YY_NEED_STRLEN
static int yy_flex_strlen (const char * s )
{
	int n;
	for ( n = 0; s[n]; ++n )
		;

	return n;
}
#endif

void *yyalloc (yy_size_t  size )
{
			return malloc(size);
}

void *yyrealloc  (void * ptr, yy_size_t  size )
{
		
	/* The cast to (char *) in the following accommodates both
	 * implementations that use char* generic pointers, and those
	 * that use void* generic pointers.  It works with the latter
	 * because both ANSI C and C++ allow castless assignment from
	 * any pointer type to void*, and deal with argument conversions
	 * as though doing an assignment.
	 */
	return realloc(ptr, size);
}

void yyfree (void * ptr )
{
			free( (char *) ptr );	/* see yyrealloc() for (char *) cast */
}

#define YYTABLES_NAME "yytables"

#line 275 "lang/lex.l"

int yywrap(void) {
    return 1;
}
#endif _LEX_YY_C

