name: CI

on:
  push:
    branches: [ main, massive-typecheck-infer-refactor ]
  pull_request:
    branches: [ main ]

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3

    - name: Install dependencies
      run: |
        sudo apt-get update
        sudo apt-get install -y \
          llvm-16 \
          llvm-16-dev \
          clang-16 \
          libreadline-dev \
          flex \
          bison

    - name: Create .env file
      run: |
        cat > .env << 'EOL'
        export CPATH=/usr/include
        export LIBRARY_PATH=/usr/lib/x86_64-linux-gnu
        export LLVM_PATH=/usr/lib/llvm-16
        EOL
    - name: Run typecheck test
      run: make test_typecheck

    - name: Run parse test
      run: make test_parse

    - name: Run scripts test
      continue-on-error: true
      run: |
        make
        chmod +x ./build/ylc
        echo "$GITHUB_WORKSPACE/build" >> $GITHUB_PATH
        make test_scripts
